name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-wheel:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inpalpra/pyprobe-ci:py3.12-qt6-v1

    steps:
      - uses: actions/checkout@v4

      - name: Build wheel
        run: python -m build --wheel

      - name: Test built wheel
        run: bash scripts/test_artifact.sh wheel
